trunk/GRF Installation/src/objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Fundraising_Event__c</fullName>
        <label>Fundraising Event</label>
        <referenceTo>Fundraising_Event__c</referenceTo>
        <relationshipName>Event_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Donations, Tickets and Comments</label>
    <nameField>
        <label>Correspondence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donations, Tickets and Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GRF Installation/src/objects/Fundraising_Event__c.object
<CustomObject>
    <fields>
        <fullName>Chapter_Logo_Alt_Text__c</fullName>
        <inlineHelpText>If you do not have logo, enter the text you want to display, most likely the name of your organization.</inlineHelpText>
        <label>Chapter Logo Alt Text</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chapter_Logo_Graphic__c</fullName>
        <formula>IMAGE(Chapter_Logo_URL__c  , &quot;Chapter Logo&quot;  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chapter Logo Display</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chapter_Logo_Height__c</fullName>
        <inlineHelpText>If your Chapter Logo is not the right size for the web page, you can adjust the image size here. If you do this, you will need to set both the height and the width.</inlineHelpText>
        <label>Optional:Chapter Logo Height in Pixels</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Chapter_Logo_URL__c</fullName>
        <inlineHelpText>Use this to add your organization&apos;s logo. Go to your web site and right click on your organization&apos;s logo. IN IE: Go to &quot;Properties&quot; and copy the URL. IN CHROME: select &quot;Copy image URL.&quot; Then paste that URL in this field.</inlineHelpText>
        <label>Chapter Logo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Chapter_Logo_Width__c</fullName>
        <inlineHelpText>If your Chapter Logo is not the right size for the web page, you can adjust the image size here. If you do this, you will need to set both the height and the width.</inlineHelpText>
        <label>Optional:Chapter Logo Width in Pixels</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Chapter__c</fullName>
        <label>Chapter</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Fundraising_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Custom_Page_Name__c</fullName>
        <inlineHelpText>This field is used to enable a custom Visualforce page that was created specially for this fundraiser.</inlineHelpText>
        <label>Custom Page Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Admission_Fee__c</fullName>
        <label>Event Admission Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_Commentary__c</fullName>
        <defaultValue>&apos;Event Commentary&apos;</defaultValue>
        <inlineHelpText>This is a field that can be updated during the event planning process. You can give your attendees info about how many people who have signed up, updates on the weather, etc. (Maximum of 30,000 characters).</inlineHelpText>
        <label>Event Update</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Cost_How_Much__c</fullName>
        <defaultValue>&apos;The price being charged for tickets&apos;</defaultValue>
        <inlineHelpText>The price you are charging for tickets. Note: only one ticket price is allowed. This is a text field, so it is possible to enter multiple prices, such as an advance price, door price and price for children.</inlineHelpText>
        <label>Event Cost (How Much)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time_When__c</fullName>
        <defaultValue>&apos;The Event Date and Time&apos;</defaultValue>
        <inlineHelpText>This is an open text box, so the Date/ Time can be formatted as you wish. A good format is &quot;January 8, 2011 8pm.&quot;</inlineHelpText>
        <label>Event Date/Time (When)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Description__c</fullName>
        <defaultValue>&apos;Event Description&apos;</defaultValue>
        <inlineHelpText>Describe the event and all the details that attendees may want to know (Maximum of 30,000 characters).</inlineHelpText>
        <label>Event Description (Body)</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Location_Where__c</fullName>
        <defaultValue>&apos;Event Location&apos;</defaultValue>
        <inlineHelpText>This is generally the address, but can also include building or a detailed description of where you&apos;re meeting.</inlineHelpText>
        <label>Event Location (Where)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Map_Graphic__c</fullName>
        <formula>Hyperlink(  Event_Map_URL__c  , &quot;Maps and Directions&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Map</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Map_URL__c</fullName>
        <inlineHelpText>Go to a mapping program, such as Maps.google.com, www.mapquest.com or maps.yahoo.com. Enter the address, city state and zip of your event. Copy the URL (it may be necessary to click &quot;Link&quot; to do so).</inlineHelpText>
        <label>Event Map URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Event_Picture_Height__c</fullName>
        <inlineHelpText>If your event photo is not the right size for the web page, you can adjust the image size here. If you do this, you will need to set both the height and the width.</inlineHelpText>
        <label>Optional:Event Photo Height in Pixels</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Picture_URL__c</fullName>
        <inlineHelpText>If you have a photo that you want to include, enter the picture URL here. For instructions see help text under &quot;Chapter Logo URL.&quot;</inlineHelpText>
        <label>Event Picture URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Event_Picture_Width__c</fullName>
        <inlineHelpText>If your event photo is not the right size for the web page, you can adjust the image size here. If you do this, you will need to set both the height and the width.</inlineHelpText>
        <label>Optional: Event Photo Width in Pixels</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Reason_and_Policies_Why__c</fullName>
        <inlineHelpText>Describe why you are hosting this event and any relevant policies, including amount that is donated per ticket (Maximum of 32,000 characters).</inlineHelpText>
        <label>Event Reason and Policies (Why)</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Tagline__c</fullName>
        <defaultValue>&apos;Event Tagline&apos;</defaultValue>
        <inlineHelpText>A tagline that describes your event and encourages people to attend (Maximum of 255 characters).</inlineHelpText>
        <label>Event Tagline</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Title__c</fullName>
        <defaultValue>&apos;Event Title&apos;</defaultValue>
        <inlineHelpText>A title that describes your event (Maximum of 60 characters).</inlineHelpText>
        <label>Event Title</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facebook_Username__c</fullName>
        <inlineHelpText>Enter your organization&apos;s Facebook Username and people can access your Facebook page through the Facebook icon.</inlineHelpText>
        <label>Facebook Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flickr_Tags__c</fullName>
        <inlineHelpText>You can give Flickr photos a &quot;tag&quot;, which is like a keyword or category label. Specifying multiple tags separated by commas shows photos with both tags (an and clause).</inlineHelpText>
        <label>Flickr Tags</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flickr_User_Id__c</fullName>
        <inlineHelpText>To include a Flickr photo stream enter the user Id.  Go to http://idgettr.com/ to determine the user id of a photo stream.</inlineHelpText>
        <label>Flickr User Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>For_more_information_contact__c</fullName>
        <defaultValue>&apos;Information regarding who to contact&apos;</defaultValue>
        <inlineHelpText>Include a person&apos;s name and his/her phone or email (Maximum of 400 characters).</inlineHelpText>
        <label>For more information contact</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Organization_Logo_Ch_Alt_Text__c</fullName>
        <defaultValue>&apos;http://www.helpsudaninternational.org/assets/images/HSlogo_grassrootsforce.jpg&apos;</defaultValue>
        <label>Organization Logo - If Ch. uses Alt Text</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Organization_Logo_Graphic__c</fullName>
        <formula>IMAGE( Organization_Logo_URL__c , &quot;Organizational Logo&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Logo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Logo_Height__c</fullName>
        <label>Organization Logo Height</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Organization_Logo_URL__c</fullName>
        <defaultValue>&apos;http://www.helpsudaninternational.org/assets/images/HSlogo_grassrootsforce.jpg&apos;</defaultValue>
        <label>Organization Logo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Organization_Logo_Width__c</fullName>
        <label>Organization Logo Width</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Method_Chapter__c</fullName>
        <inlineHelpText>This field is used to indicate and describe a payment method directly to the chapter.  For example &apos;Pay in advance at the community center .&apos;  Leave the field blank if this is not an option.</inlineHelpText>
        <label>Payment Method:Chapter</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method_Door__c</fullName>
        <inlineHelpText>This field is used to indicate and describe a payment method that takes place at the beginning or an event.  For example &apos;Pay at the door&apos;  or &apos;Pay on the bus.&apos;</inlineHelpText>
        <label>Payment Method:Door</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method_Organization__c</fullName>
        <inlineHelpText>This field is used to indicate and describe a payment method directly to the organization.  For example &apos;Send a check to ....&apos;.  Leave the field blank if this is not an option.</inlineHelpText>
        <label>Payment Method:Organization</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method_Website__c</fullName>
        <defaultValue>&apos;Pay by Credit Card&apos;</defaultValue>
        <inlineHelpText>This field is used to indicate and describe a payment method, for example &apos;Register and Donate Now!&apos; or &apos; Pay by Credit Card.&apos;</inlineHelpText>
        <label>Payment Method:Website</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Description__c</fullName>
        <inlineHelpText>Details about registration, such as how to register in person, registration deadline, etc.</inlineHelpText>
        <label>Registration Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Site_Type__c</fullName>
        <formula>If(begins($RecordType.Name,&apos;Donation&apos;),&apos;Donation&apos;,&apos;Registration&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Social_Media_Links_Label__c</fullName>
        <inlineHelpText>This is the header next to the Twitter and Facebook Icon. Possible text: &quot;Click here to follow us on Twitter or Facebook:&quot;</inlineHelpText>
        <label>Social Media Links Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support__c</fullName>
        <defaultValue>&apos;Optional description of what the fundraising event supports.&apos;</defaultValue>
        <inlineHelpText>Describe what the fundraising event supports.</inlineHelpText>
        <label>Support</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Twitter_Search_Terms__c</fullName>
        <inlineHelpText>If you enter a Twitter search term, you will have a rolling list of Twitter searches on your page. Create a hash tag for your event or use a common term for your cause. If you do not want this feature, leave this field blank.</inlineHelpText>
        <label>Twitter Search Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Twitter_Username__c</fullName>
        <inlineHelpText>Enter your organization&apos;s Twitter Username and people can access your Twitter page through the Twitter icon.</inlineHelpText>
        <label>Twitter Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Fundraising Site</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fundraising Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GRF Installation/src/classes/GRF_EventRegistrationController.cls
public class GRF_EventRegistrationController {
        public Correspondence__c c {get; set;}
        public Fundraising_Event__c theEvent {get;set;}
        public GRF_EventRegistrationController() { 
        c = new Correspondence__c();   
        String EventId = ApexPages.currentPage().getParameters().get('id');
        System.debug('*** EventId '+ EventId);
         if (EventId != null) { 
            theEvent = [Select id, Name,Chapter__c,Chapter_Logo_Graphic__c,Chapter_Logo_URL__c,
             Chapter_Logo_Width__c,Chapter_Logo_Height__c,Organization_Logo_URL__c, 
             Organization_Logo_Width__c,Organization_Logo_Height__c,Organization_Logo_Graphic__c,
             Event_Picture_URL__c, Event_Picture_Width__c,Event_Picture_Height__c,Event_Commentary__c,
             Event_Date__c,Event_Description__c, Event_Date_Time_When__c,
             Event_Location_Where__c, Event_Reason_and_Policies_Why__c, Event_Cost_How_Much__c, 
             Event_Map_Graphic__c ,Event_Map_URL__c, Event_Admission_Fee__c, Twitter_Username__c,
             Facebook_Username__c, Custom_Page_Name__c, Twitter_Search_Terms__c,
             Site_Type__c,For_more_information_contact__c,Event_Title__c,Event_Tagline__c,
             Support__c,Social_Media_Links_Label__c,Organization_Logo_Ch_Alt_Text__c,Chapter_Logo_Alt_Text__c,
             Flickr_Tags__c, Flickr_User_Id__c,Registration_Description__c, 
             Payment_Method_Website__c,Payment_Method_Door__c,Payment_Method_Chapter__c,
             Payment_Method_Organization__c,Chapter__r.Name,Event_Plan_Reviewed__c,Site_Closed__c,
             Funds_Raised_to_Date__c,Expected_Revenue__c,Display_Fundraising_Progress_Graphic__c,
             Payment_Processing_Page__c
             From Fundraising_Event__c 
                where id = :EventId LIMIT 1];
             }  
          else { 
             theEvent = [Select id,Name, Chapter__c,Chapter_Logo_Graphic__c,Chapter_Logo_URL__c,
             Chapter_Logo_Width__c,Chapter_Logo_Height__c,Organization_Logo_URL__c, 
             Organization_Logo_Width__c, Organization_Logo_Height__c,Organization_Logo_Graphic__c,
             Event_Picture_URL__c, Event_Picture_Width__c,Event_Picture_Height__c,Event_Commentary__c,
             Event_Date__c,Event_Description__c, Event_Date_Time_When__c,
             Event_Location_Where__c, Event_Reason_and_Policies_Why__c,
             Event_Cost_How_Much__c,Event_Map_Graphic__c,Event_Map_URL__c,Event_Admission_Fee__c,
             Twitter_Username__c,Facebook_Username__c, Custom_Page_Name__c,
             Twitter_Search_Terms__c ,Site_Type__c,For_more_information_contact__c,
             Event_Title__c,Event_Tagline__c , Support__c ,Social_Media_Links_Label__c,
             Organization_Logo_Ch_Alt_Text__c,Chapter_Logo_Alt_Text__c,
             Flickr_Tags__c, Flickr_User_Id__c,Registration_Description__c, 
             Payment_Method_Website__c,Payment_Method_Door__c,Payment_Method_Chapter__c,
             Payment_Method_Organization__c,Chapter__r.Name,Event_Plan_Reviewed__c,Site_Closed__c,
             Funds_Raised_to_Date__c,Expected_Revenue__c,Display_Fundraising_Progress_Graphic__c,
             Payment_Processing_Page__c
            From Fundraising_Event__c LIMIT 1];
         } 
         c.Fundraising_Event__c = theEvent.id; 
         Try {
           If (theEvent.Custom_Page_Name__c.length()==0)
             {theEvent.Custom_Page_Name__c = 'GRF_EventBlankPage'; }}
          Catch(exception e)
             {theEvent.Custom_Page_Name__c = 'GRF_EventBlankPage'; }
        } 

  
  public PageReference Print() {
    return Page.GRF_EventPDF; 
    } 

  public PageReference Register() {  
    System.debug('*** Registration ');
    Boolean isError = false;
    String strName = theEvent.Name +'-' + system.today()+': ' +c.First_Name__c +' ' +c.Last_Name__c;
    if (strName.length() > 80){
         strName = strName.substring(0,79);
     }            
     c.Source__c = 'Website';
     c.Name = strName;         
     try {
       If ( theEvent.Site_Type__c =='Donation' &&   c.Payment_Method__c == null){
        c.Payment_Method__c = 'Website';}   
       System.debug('*** Corr. Name' + c.name);  
       insert c;  
     }
     catch (Exception e) {
        System.debug('**** ' + e);    
        ApexPages.addMessages(e); 
        isError = true;   
        return Page.GRF_EventRegistration; 
      }            
      System.debug ('*** Payment Method '+ c.Payment_Method__c 
        +'&'+ApexPages.currentPage().getParameters().get('PaymentMethod') );
      If (c.Payment_Method__c =='Website' || theEvent.Site_Type__c =='Donation'  ||
           ApexPages.currentPage().getParameters().get('PaymentMethod')=='Website'){
           System.debug('*** Paying by Credit Card' + theEvent.Site_Type__c  + '****');
      
      /* If using Google Checkout
           PageReference pr;  
           pr = Page.GoogleRedirectV2;
           pr.getParameters().put('item_name_1','HELPSudanDonation');
           pr.getParameters().put('item_description_1','HELPSudanDonation (Id =' +c.Id +')');
           pr.getParameters().put('item_quantity_1','1');
           pr.getParameters().put('item_price_1',c.Amount_Donated_through_Org_Website__c.format());
           pr.getParameters().put('item_merchant_id_1',c.Id); 
           pr.getParameters().put('item_name_2','Admission');             
           pr.getParameters().put('item_description_2','Admission (Id =' +c.Id +')');
           pr.getParameters().put('item_quantity_2',c.Number_Planning_to_Attend__c.format());
           pr.getParameters().put('item_price_2',theEvent.Event_Admission_Fee__c.format());
           pr.getParameters().put('item_merchant_id_2',c.Id);
        */              
       
       // Payment Connect Processing
         PageReference pr = new PageReference(theEvent.Payment_Processing_Page__c);
         string cId =c.Id;
         system.debug('*** Correspondence Id' + cId);
         c = [Select Id,last_name__c, first_name__c, email__c,
             Amount_Donated_through_Org_Website__c,Number_Planning_to_Attend__c,
             Admissions_Fee_Paid_Through_Org_Website__c           
             from Correspondence__c where id=:cId limit 1] ;       
         pr.getParameters().put('eventid',theEvent.Id);
         pr.getParameters().put('firstname',c.first_name__c);
         try 
           {pr.getParameters().put('lastname',c.last_name__c);}
         catch(exception e){}
         try {pr.getParameters().put('email',c.email__c);}
         catch(exception e){}
         try {pr.getParameters().put('donationamount',c.Amount_Donated_through_Org_Website__c.format());} 
         catch(exception e)
           { pr.getParameters().put('donationamount','0');} 
        try{
          pr.getParameters().put('admissionfee',c.Admissions_Fee_Paid_Through_Org_Website__c.format());
         }
         catch(exception e){pr.getParameters().put('admissionfee','0');}
         pr.getParameters().put('correspondenceid',c.Id);
       // end of Payment Connect Processing
         return pr;   
       } 
       else{
       return page.GRF_EventRegistrationThankYou;} }
     
       public static testmethod void SuccessValidId (){
        System.debug('*** Test Create a New Opportunity');
        Opportunity o = new opportunity (Stagename = 'Open',
          closedate = system.date.today(),
          Name = 'Test1', grf01_Fundraising_Event_Name__c = 'Test1');
        insert o;  
        System.debug('*** Test Create a New Fundraising Event');
        Fundraising_Event__c f = new Fundraising_Event__c() ;
        f.Name='Test1';
        insert f;
          Test.setCurrentPageReference(new PageReference('Page.GRF_EventRegistration')); 
          System.currentPageReference().getParameters().put('id', f.id);
          System.currentPageReference().getParameters().put('PaymentMethod', 'Website');
          System.debug ('*** Fundraiser Id ' + ApexPages.currentPage().getParameters().get('id') );         
          GRF_EventRegistrationController controller = new GRF_EventRegistrationController();
          Correspondence__c corr = new Correspondence__c (Name = 'Test1', First_Name__c = 'Test 1', 
            Last_Name__c = 'Test 1', Fundraising_Event__c = f.id, Amount_Paid_to_Chapter__c = 10,
            email__c='test1@test.com',Payment_Method__c = 'Website' 
            );
          Controller.c=corr;
          Controller.Print();
          Controller.Register();
        corr.Amount_Paid_to_Chapter__c = 20;
        corr.status__c = 'Payment Completed';
        update corr;  
        
       }
        public static testmethod void SuccessInvalidId (){
        Fundraising_Event__c F = new Fundraising_Event__c() ;
        F.Name='Test2';
        insert F;
          Test.setCurrentPageReference(new PageReference('Page.GRF_EventRegistration')); 
          GRF_EventRegistrationController controller = new GRF_EventRegistrationController();
          Test.setCurrentPageReference(new PageReference('Page.GRF_EventRegistration'));
          Correspondence__c corr = new Correspondence__c (Name = 'Test 2', First_Name__c = 'Test 2', 
            Last_Name__c = 'Test 2', Fundraising_Event__c = f.id, Amount_Paid_to_Chapter__c = 10,
            email__c='test2@test.com',Payment_Method__c = 'Door' 
            );
          Controller.c=corr;
          Controller.Print(); 
          Controller.Register();
       }
       }